---
# scrape_shield file for revboot/cloudflare.zone_settings

- name: "Configure Scrape Shield settings"
  ansible.builtin.include_role:
    name: "linuxhq.cloudflare.scrape_shield"
  vars:
    cf_account_name: "{{ cloudflare_auth_account_name }}" # noqa: var-naming[no-role-prefix]
    cf_auth_token: "{{ cloudflare_auth_api_token }}" # noqa: var-naming[no-role-prefix]
    cf_scrape_shield: "{{ cloudflare_zone_config.scrape_shield }}" # noqa: var-naming[no-role-prefix]
