---
# ssl file for revboot/cloudflare.zone

- name: "Configure SSL/TLS settings"
  ansible.builtin.include_role:
    name: "linuxhq.cloudflare.ssl"
  vars:
    cf_account_name: "{{ cloudflare_auth_account_name }}" # noqa: var-naming[no-role-prefix]
    cf_auth_token: "{{ cloudflare_auth_api_token }}" # noqa: var-naming[no-role-prefix]
    cf_ssl: "{{ cloudflare_zone_config.ssl }}" # noqa: var-naming[no-role-prefix]
