---
# facts file for revboot/cloudflare.ruleset

- name: "Set variables for Ruleset"
  ansible.builtin.set_fact:
    cloudflare_ruleset_config:
      rulesets:
        http_request_dynamic_redirect: "{{ cloudflare_ruleset_defaults.rulesets.http_request_dynamic_redirect
          | ansible.builtin.union(cloudflare_zone.rulesets.http_request_dynamic_redirect | default([])) }}"

- name: "Print variables"
  ansible.builtin.debug:
    msg:
      - "{{ cloudflare_zone.name | default() }}"
      - "{{ cloudflare_ruleset_config | default() }}"
