---
# http_request_dynamic_redirect file for revboot/cloudflare.ruleset

- name: "Configure Ruleset http_request_dynamic_redirect"
  ansible.builtin.include_role:
    name: "linuxhq.cloudflare.ruleset_entrypoint"
  vars:
    cf_account_name: "{{ cloudflare_auth_account_name }}" # noqa: var-naming[no-role-prefix]
    cf_auth_token: "{{ cloudflare_auth_api_token }}" # noqa: var-naming[no-role-prefix]
    cf_zone_id: "{{ _cf_zone_id[cloudflare_zone.name] }}" # noqa: var-naming[no-role-prefix]
    cf_ruleset_phase: "http_request_dynamic_redirect" # noqa: var-naming[no-role-prefix]
    cf_ruleset_rules: "{{ cloudflare_ruleset_config.rulesets.http_request_dynamic_redirect }}" # noqa: var-naming[no-role-prefix]
