---
# facts file for revboot/cloudflare.init

- name: "Get Zone Info"
  ansible.builtin.include_role:
    name: "linuxhq.cloudflare.zone_info"
  vars:
    cf_account_name: "{{ cloudflare_auth_account_name }}" # noqa: var-naming[no-role-prefix]
    cf_auth_token: "{{ cloudflare_auth_api_token }}" # noqa: var-naming[no-role-prefix]
    cf_zones_match: "{{ cloudflare_paging_match }}" # noqa: var-naming[no-role-prefix]
    cf_zones_page: "{{ cloudflare_paging_page_number }}" # noqa: var-naming[no-role-prefix]
    cf_zones_per_page: "{{ cloudflare_paging_zones_per_page }}" # noqa: var-naming[no-role-prefix]
